---
- name: enable overlay module
  lineinfile:
    dest: /etc/modules-load.d/overlay.conf
    state: present
    create: yes
    line: 'overlay'
  when:
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: load overlay module
  modprobe:
    name: overlay
    state: present
  when:
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: create docker systemd directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    mode: 0755
  when:
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: configure docker to use overlay driver
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: 0644
    force: yes
  notify:
  - restart docker
  when:
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: Install Docker RPM
  yum:
    name:   http://{{ eva-tech_repository_url }}:{{ eva-tech_repository_port }}/repository/eva-tech/rpms/docker-ce-18.06.1.ce-3.el7.x86_64.rpm
    state: present
  when:
  - "'bastion_host' in group_names"
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: Install Docker RPM
  yum:
    name:  http://bastion_host1.{{ internal_subdomain }}:{{ bastion_host_nexus_port }}/repository/eva-tech/rpms/docker-ce-18.06.1.ce-3.el7.x86_64.rpm
    state: present
  when:
  - "'bastion_host' not in group_names"
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: Install Docker Py
  yum:
    name: docker-python
    state: installed
  when:
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: Enable Docker
  service:
    name: docker
    enabled: yes
    state: started
  when:
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: allow the default user to use docker
  user:
    name: centos
    groups: docker
    append: yes
  when:
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: Configure docker to for use bastion_host as insecure registry
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
  - restart docker
  when:
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: Enable Docker
  service:
    name: docker
    state: stopped
  when:
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: Enable Docker
  service:
    name: docker
    state: started
  when:
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: Docker Login for use dockeregistry.eva-tech.com
  docker_login:
    registry: "{{ eva-tech_repository_url }}:{{ docker_port}}"
    username: "{{ docker_login_user }}"
    password: "{{ docker_login_password }}"
  when:
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

- name: Docker Login for use bastion_host
  docker_login:
    registry: bastion_host1.{{ internal_subdomain }}:{{ docker_port }}
    username: "{{ docker_login_user }}"
    password: "{{ docker_login_password }}"
  when:
  - "'bastion_host' not in group_names"
  - "'NameNode' not in group_names"
  - "'DataNode' not in group_names"
  tags:
  - docker

